// Code generated by cmd/baton-ts-sdk from baton-sdk v0.24.1. DO NOT EDIT.
//
// Type declarations for the generated annotation helpers exposed via
// @baton/helpers.annotations. The runtime implementation lives in
// pkg/jsruntime/modules.go; this file just mirrors the auto-generated
// call surface for TypeScript consumers.

import type {
  AccountInfo,
  AgentTrait,
  Aliases,
  AppTrait,
  AssetRef,
  BatonActionSchema,
  BatonID,
  CapabilityPermission,
  CapabilityPermissions,
  ChildResourceType,
  ConfigSchema,
  ConnectorAccountCreationSchema,
  ConnectorAccountCreationSchema_Field,
  ConnectorCapabilities,
  ConnectorMetadata,
  CreateGrantEvent,
  CreateRevokeEvent,
  CredentialDetails,
  CredentialDetailsAccountProvisioning,
  CredentialDetailsCredentialIssue,
  CredentialDetailsCredentialRotation,
  CredentialIssueOptionDescriptor,
  CredentialIssueOptions,
  CredentialOptions,
  Deprecated,
  DeviceOS,
  ETag,
  ETagMatch,
  ETagMetadata,
  EncryptedData,
  EncryptionConfig,
  EnqueuePageTokens,
  Entitlement,
  EntitlementExclusionGroup,
  EntitlementImmutable,
  Event,
  EventFeedMetadata,
  ExternalId,
  ExternalLink,
  ExternalResourceMatch,
  ExternalResourceMatchAll,
  ExternalResourceMatchID,
  ExternalTicketRef,
  ExternalTicketSettings,
  Field,
  FileField,
  Grant,
  GrantAlreadyExists,
  GrantAlreadyRevoked,
  GrantEvent,
  GrantExpandable,
  GrantImmutable,
  GrantMetadata,
  GrantReplaced,
  GrantSources,
  GrantSources_GrantSource,
  GroupTrait,
  InsertResourceGrants,
  IssuanceExpiryCapability,
  Issue,
  KeyGenerationProfile,
  LicenseProfileTrait,
  LineItem,
  LocalCredentialOptions,
  ManagedDeviceTrait,
  Money,
  NonHumanIdentityTrait,
  OptInRequired,
  PasswordConstraint,
  PlaintextData,
  RandomStringField,
  RateLimitDescription,
  RateLimitWaitReport,
  RawId,
  RequestId,
  Resource,
  ResourceChangeEvent,
  ResourceDeleted,
  ResourceDoesNotExist,
  ResourceId,
  ResourceType,
  ResourceTypeCapability,
  ResourceType_Trait,
  RevokeEvent,
  RiskFactor,
  RiskScore,
  RoleScopeCondition,
  RoleScopeConditions,
  RoleTrait,
  ScopeBindingTrait,
  SecretTrait,
  SecurityInsightTrait,
  SelectField,
  SessionStoreUsage,
  SkipEntitlements,
  SkipEntitlementsAndGrants,
  SkipGrants,
  SkipSyncAnomalyDetection,
  SourceCacheCapability,
  SourceCacheLookupAnswers,
  SourceCacheLookupAsk,
  SourceCacheLookupAsk_Query,
  SourceCacheLookupOffer,
  SourceCacheRecord,
  SourceCacheReplay,
  Status,
  StringField,
  Ticket,
  TicketCustomField,
  TicketCustomFieldBoolValue,
  TicketCustomFieldNumberValue,
  TicketCustomFieldObjectValue,
  TicketCustomFieldPickMultipleObjectValues,
  TicketCustomFieldPickMultipleStringValues,
  TicketCustomFieldPickObjectValue,
  TicketCustomFieldPickStringValue,
  TicketCustomFieldStringValue,
  TicketCustomFieldStringValues,
  TicketCustomFieldTimestampValue,
  TicketRequest,
  TicketSchema,
  TicketStatus,
  TicketType,
  TicketsServiceBulkCreateTicketsRequest,
  TicketsServiceBulkCreateTicketsResponse,
  TicketsServiceBulkGetTicketsRequest,
  TicketsServiceBulkGetTicketsResponse,
  TicketsServiceCreateTicketRequest,
  TicketsServiceCreateTicketResponse,
  TicketsServiceGetTicketRequest,
  TicketsServiceGetTicketResponse,
  TicketsServiceGetTicketSchemaRequest,
  TicketsServiceGetTicketSchemaResponse,
  TicketsServiceListTicketSchemasRequest,
  TicketsServiceListTicketSchemasResponse,
  TypeScopedEntitlements,
  TypeScopedGrants,
  UsageEvent,
  UserTrait,
  V1Identifier,
  VendorAgreementTrait,
  VendorTrait,
} from "./sdk-types";

export interface GeneratedAnnotations {
  accountInfo<T extends Omit<AccountInfo, "@type">>(spec: T): AccountInfo;
  agentTrait<T extends Omit<AgentTrait, "@type">>(spec: T): AgentTrait;
  aliases(ids: readonly string[]): Aliases;
  appTrait<T extends Omit<AppTrait, "@type">>(spec: T): AppTrait;
  assetRef(id: string): AssetRef;
  batonActionSchema<T extends Omit<BatonActionSchema, "@type">>(spec: T): BatonActionSchema;
  batonID(): BatonID;
  capabilityPermission(permission: string): CapabilityPermission;
  capabilityPermissions<T extends Omit<CapabilityPermissions, "@type">>(spec: T): CapabilityPermissions;
  childResourceType(resourceTypeId: string): ChildResourceType;
  configSchema<T extends Omit<ConfigSchema, "@type">>(spec: T): ConfigSchema;
  connectorAccountCreationSchema(fieldMap: Record<string, ConnectorAccountCreationSchema_Field>): ConnectorAccountCreationSchema;
  connectorCapabilities<T extends Omit<ConnectorCapabilities, "@type">>(spec: T): ConnectorCapabilities;
  connectorMetadata<T extends Omit<ConnectorMetadata, "@type">>(spec: T): ConnectorMetadata;
  createGrantEvent<T extends Omit<CreateGrantEvent, "@type">>(spec: T): CreateGrantEvent;
  createRevokeEvent<T extends Omit<CreateRevokeEvent, "@type">>(spec: T): CreateRevokeEvent;
  credentialDetails<T extends Omit<CredentialDetails, "@type">>(spec: T): CredentialDetails;
  credentialDetailsAccountProvisioning<T extends Omit<CredentialDetailsAccountProvisioning, "@type">>(spec: T): CredentialDetailsAccountProvisioning;
  credentialDetailsCredentialIssue<T extends Omit<CredentialDetailsCredentialIssue, "@type">>(spec: T): CredentialDetailsCredentialIssue;
  credentialDetailsCredentialRotation<T extends Omit<CredentialDetailsCredentialRotation, "@type">>(spec: T): CredentialDetailsCredentialRotation;
  credentialIssueOptionDescriptor<T extends Omit<CredentialIssueOptionDescriptor, "@type">>(spec: T): CredentialIssueOptionDescriptor;
  credentialIssueOptions<T extends Omit<CredentialIssueOptions, "@type">>(spec: T): CredentialIssueOptions;
  credentialOptions<T extends Omit<CredentialOptions, "@type">>(spec: T): CredentialOptions;
  deprecated(): Deprecated;
  deviceOS<T extends Omit<DeviceOS, "@type">>(spec: T): DeviceOS;
  eTag<T extends Omit<ETag, "@type">>(spec: T): ETag;
  eTagMatch(entitlementId: string): ETagMatch;
  eTagMetadata<T extends Omit<ETagMetadata, "@type">>(spec: T): ETagMetadata;
  encryptedData<T extends Omit<EncryptedData, "@type">>(spec: T): EncryptedData;
  encryptionConfig<T extends Omit<EncryptionConfig, "@type">>(spec: T): EncryptionConfig;
  enqueuePageTokens<T extends Omit<EnqueuePageTokens, "@type">>(spec: T): EnqueuePageTokens;
  entitlement<T extends Omit<Entitlement, "@type">>(spec: T): Entitlement;
  entitlementExclusionGroup<T extends Omit<EntitlementExclusionGroup, "@type">>(spec: T): EntitlementExclusionGroup;
  entitlementImmutable<T extends Omit<EntitlementImmutable, "@type">>(spec: T): EntitlementImmutable;
  event<T extends Omit<Event, "@type">>(spec: T): Event;
  eventFeedMetadata<T extends Omit<EventFeedMetadata, "@type">>(spec: T): EventFeedMetadata;
  externalId<T extends Omit<ExternalId, "@type">>(spec: T): ExternalId;
  externalLink(url: string): ExternalLink;
  externalResourceMatch<T extends Omit<ExternalResourceMatch, "@type">>(spec: T): ExternalResourceMatch;
  externalResourceMatchAll(resourceType: ResourceType_Trait): ExternalResourceMatchAll;
  externalResourceMatchID(id: string): ExternalResourceMatchID;
  externalTicketRef<T extends Omit<ExternalTicketRef, "@type">>(spec: T): ExternalTicketRef;
  externalTicketSettings(enabled: boolean): ExternalTicketSettings;
  field<T extends Omit<Field, "@type">>(spec: T): Field;
  fileField<T extends Omit<FileField, "@type">>(spec: T): FileField;
  grant<T extends Omit<Grant, "@type">>(spec: T): Grant;
  grantAlreadyExists(): GrantAlreadyExists;
  grantAlreadyRevoked(): GrantAlreadyRevoked;
  grantEvent<T extends Omit<GrantEvent, "@type">>(spec: T): GrantEvent;
  grantExpandable<T extends Omit<GrantExpandable, "@type">>(spec: T): GrantExpandable;
  grantImmutable<T extends Omit<GrantImmutable, "@type">>(spec: T): GrantImmutable;
  grantMetadata<T extends Omit<GrantMetadata, "@type">>(spec: T): GrantMetadata;
  grantReplaced(replacedGrantId: string): GrantReplaced;
  grantSources(sources: Record<string, GrantSources_GrantSource>): GrantSources;
  groupTrait<T extends Omit<GroupTrait, "@type">>(spec: T): GroupTrait;
  insertResourceGrants(): InsertResourceGrants;
  issuanceExpiryCapability<T extends Omit<IssuanceExpiryCapability, "@type">>(spec: T): IssuanceExpiryCapability;
  issue<T extends Omit<Issue, "@type">>(spec: T): Issue;
  keyGenerationProfile<T extends Omit<KeyGenerationProfile, "@type">>(spec: T): KeyGenerationProfile;
  licenseProfileTrait<T extends Omit<LicenseProfileTrait, "@type">>(spec: T): LicenseProfileTrait;
  lineItem<T extends Omit<LineItem, "@type">>(spec: T): LineItem;
  localCredentialOptions<T extends Omit<LocalCredentialOptions, "@type">>(spec: T): LocalCredentialOptions;
  managedDeviceTrait<T extends Omit<ManagedDeviceTrait, "@type">>(spec: T): ManagedDeviceTrait;
  money<T extends Omit<Money, "@type">>(spec: T): Money;
  nonHumanIdentityTrait<T extends Omit<NonHumanIdentityTrait, "@type">>(spec: T): NonHumanIdentityTrait;
  optInRequired(): OptInRequired;
  passwordConstraint<T extends Omit<PasswordConstraint, "@type">>(spec: T): PasswordConstraint;
  plaintextData<T extends Omit<PlaintextData, "@type">>(spec: T): PlaintextData;
  randomStringField(length: number): RandomStringField;
  rateLimitDescription<T extends Omit<RateLimitDescription, "@type">>(spec: T): RateLimitDescription;
  rateLimitWaitReport(waitMs: string): RateLimitWaitReport;
  rawId(id: string): RawId;
  requestId(requestId: string): RequestId;
  resource<T extends Omit<Resource, "@type">>(spec: T): Resource;
  resourceChangeEvent<T extends Omit<ResourceChangeEvent, "@type">>(spec: T): ResourceChangeEvent;
  resourceDeleted(resourceId: ResourceId): ResourceDeleted;
  resourceDoesNotExist(): ResourceDoesNotExist;
  resourceId<T extends Omit<ResourceId, "@type">>(spec: T): ResourceId;
  resourceType<T extends Omit<ResourceType, "@type">>(spec: T): ResourceType;
  resourceTypeCapability<T extends Omit<ResourceTypeCapability, "@type">>(spec: T): ResourceTypeCapability;
  revokeEvent<T extends Omit<RevokeEvent, "@type">>(spec: T): RevokeEvent;
  riskFactor<T extends Omit<RiskFactor, "@type">>(spec: T): RiskFactor;
  riskScore<T extends Omit<RiskScore, "@type">>(spec: T): RiskScore;
  roleScopeCondition(expression: string): RoleScopeCondition;
  roleScopeConditions<T extends Omit<RoleScopeConditions, "@type">>(spec: T): RoleScopeConditions;
  roleTrait<T extends Omit<RoleTrait, "@type">>(spec: T): RoleTrait;
  scopeBindingTrait<T extends Omit<ScopeBindingTrait, "@type">>(spec: T): ScopeBindingTrait;
  secretTrait<T extends Omit<SecretTrait, "@type">>(spec: T): SecretTrait;
  securityInsightTrait<T extends Omit<SecurityInsightTrait, "@type">>(spec: T): SecurityInsightTrait;
  selectField<T extends Omit<SelectField, "@type">>(spec: T): SelectField;
  sessionStoreUsage<T extends Omit<SessionStoreUsage, "@type">>(spec: T): SessionStoreUsage;
  skipEntitlements(): SkipEntitlements;
  skipEntitlementsAndGrants(): SkipEntitlementsAndGrants;
  skipGrants(): SkipGrants;
  skipSyncAnomalyDetection(): SkipSyncAnomalyDetection;
  sourceCacheCapability<T extends Omit<SourceCacheCapability, "@type">>(spec: T): SourceCacheCapability;
  sourceCacheLookupAnswers<T extends Omit<SourceCacheLookupAnswers, "@type">>(spec: T): SourceCacheLookupAnswers;
  sourceCacheLookupAsk(queries: readonly SourceCacheLookupAsk_Query[]): SourceCacheLookupAsk;
  sourceCacheLookupOffer(): SourceCacheLookupOffer;
  sourceCacheRecord<T extends Omit<SourceCacheRecord, "@type">>(spec: T): SourceCacheRecord;
  sourceCacheReplay<T extends Omit<SourceCacheReplay, "@type">>(spec: T): SourceCacheReplay;
  status<T extends Omit<Status, "@type">>(spec: T): Status;
  stringField<T extends Omit<StringField, "@type">>(spec: T): StringField;
  ticket<T extends Omit<Ticket, "@type">>(spec: T): Ticket;
  ticketCustomField<T extends Omit<TicketCustomField, "@type">>(spec: T): TicketCustomField;
  ticketCustomFieldBoolValue(value: boolean): TicketCustomFieldBoolValue;
  ticketCustomFieldNumberValue<T extends Omit<TicketCustomFieldNumberValue, "@type">>(spec: T): TicketCustomFieldNumberValue;
  ticketCustomFieldObjectValue<T extends Omit<TicketCustomFieldObjectValue, "@type">>(spec: T): TicketCustomFieldObjectValue;
  ticketCustomFieldPickMultipleObjectValues<T extends Omit<TicketCustomFieldPickMultipleObjectValues, "@type">>(spec: T): TicketCustomFieldPickMultipleObjectValues;
  ticketCustomFieldPickMultipleStringValues<T extends Omit<TicketCustomFieldPickMultipleStringValues, "@type">>(spec: T): TicketCustomFieldPickMultipleStringValues;
  ticketCustomFieldPickObjectValue<T extends Omit<TicketCustomFieldPickObjectValue, "@type">>(spec: T): TicketCustomFieldPickObjectValue;
  ticketCustomFieldPickStringValue<T extends Omit<TicketCustomFieldPickStringValue, "@type">>(spec: T): TicketCustomFieldPickStringValue;
  ticketCustomFieldStringValue<T extends Omit<TicketCustomFieldStringValue, "@type">>(spec: T): TicketCustomFieldStringValue;
  ticketCustomFieldStringValues<T extends Omit<TicketCustomFieldStringValues, "@type">>(spec: T): TicketCustomFieldStringValues;
  ticketCustomFieldTimestampValue<T extends Omit<TicketCustomFieldTimestampValue, "@type">>(spec: T): TicketCustomFieldTimestampValue;
  ticketRequest<T extends Omit<TicketRequest, "@type">>(spec: T): TicketRequest;
  ticketSchema<T extends Omit<TicketSchema, "@type">>(spec: T): TicketSchema;
  ticketStatus<T extends Omit<TicketStatus, "@type">>(spec: T): TicketStatus;
  ticketType<T extends Omit<TicketType, "@type">>(spec: T): TicketType;
  ticketsServiceBulkCreateTicketsRequest<T extends Omit<TicketsServiceBulkCreateTicketsRequest, "@type">>(spec: T): TicketsServiceBulkCreateTicketsRequest;
  ticketsServiceBulkCreateTicketsResponse<T extends Omit<TicketsServiceBulkCreateTicketsResponse, "@type">>(spec: T): TicketsServiceBulkCreateTicketsResponse;
  ticketsServiceBulkGetTicketsRequest<T extends Omit<TicketsServiceBulkGetTicketsRequest, "@type">>(spec: T): TicketsServiceBulkGetTicketsRequest;
  ticketsServiceBulkGetTicketsResponse<T extends Omit<TicketsServiceBulkGetTicketsResponse, "@type">>(spec: T): TicketsServiceBulkGetTicketsResponse;
  ticketsServiceCreateTicketRequest<T extends Omit<TicketsServiceCreateTicketRequest, "@type">>(spec: T): TicketsServiceCreateTicketRequest;
  ticketsServiceCreateTicketResponse<T extends Omit<TicketsServiceCreateTicketResponse, "@type">>(spec: T): TicketsServiceCreateTicketResponse;
  ticketsServiceGetTicketRequest<T extends Omit<TicketsServiceGetTicketRequest, "@type">>(spec: T): TicketsServiceGetTicketRequest;
  ticketsServiceGetTicketResponse<T extends Omit<TicketsServiceGetTicketResponse, "@type">>(spec: T): TicketsServiceGetTicketResponse;
  ticketsServiceGetTicketSchemaRequest<T extends Omit<TicketsServiceGetTicketSchemaRequest, "@type">>(spec: T): TicketsServiceGetTicketSchemaRequest;
  ticketsServiceGetTicketSchemaResponse<T extends Omit<TicketsServiceGetTicketSchemaResponse, "@type">>(spec: T): TicketsServiceGetTicketSchemaResponse;
  ticketsServiceListTicketSchemasRequest<T extends Omit<TicketsServiceListTicketSchemasRequest, "@type">>(spec: T): TicketsServiceListTicketSchemasRequest;
  ticketsServiceListTicketSchemasResponse<T extends Omit<TicketsServiceListTicketSchemasResponse, "@type">>(spec: T): TicketsServiceListTicketSchemasResponse;
  typeScopedEntitlements(): TypeScopedEntitlements;
  typeScopedGrants(): TypeScopedGrants;
  usageEvent<T extends Omit<UsageEvent, "@type">>(spec: T): UsageEvent;
  userTrait<T extends Omit<UserTrait, "@type">>(spec: T): UserTrait;
  v1Identifier(id: string): V1Identifier;
  vendorAgreementTrait<T extends Omit<VendorAgreementTrait, "@type">>(spec: T): VendorAgreementTrait;
  vendorTrait<T extends Omit<VendorTrait, "@type">>(spec: T): VendorTrait;
}
