// Code generated by cmd/baton-ts-host. DO NOT EDIT.
// Regenerate with: make build-host-capabilities-types

export interface CacheGetManyArgs {
  namespace: string;
  scopes: string[];
  keys: string[];
}

export interface CacheGetManyResult {
  effectiveScope: string;
  hits: Record<string, unknown>;
}

export interface CacheSetManyArgs {
  namespace: string;
  effectiveScope: string;
  values: Record<string, unknown>;
}

export interface CacheSetManyResult {
}

export interface ConfigGetArgs {
  name: string;
}

export interface FusedSiblingFetchSpec {
  name: string;
  label: string;
  transportName: string;
  request: Record<string, unknown>;
  itemsPath: string[];
  pagination?: Record<string, unknown>;
  mode: string;
  projectionId: string;
}

export interface LoadFusedSiblingResponsesArgs {
  specs: FusedSiblingFetchSpec[];
}

export interface LoadFusedSiblingResponsesResult {
  results: Record<string, unknown>;
}

export interface LoadShapedResponseArgs {
  transportName: string;
  request: Record<string, unknown>;
  itemsPath?: string[];
  pagination?: Record<string, unknown>;
  mode?: string;
}

export interface LoadShapedResponseResult {
  value: unknown;
  nextPageToken: string;
}

export interface LogArgs {
  message: string;
  fields?: Record<string, unknown>;
}

export interface LogResult {
}

export interface PhaseObserveArgs {
  id: string;
  granularity?: string;
  actionPath?: string[];
  payload?: Record<string, unknown>;
}

export interface PhaseObserveResult {
}

export interface PhaseWantsArgs {
  id: string;
  granularity?: string;
  actionPath?: string[];
}

export interface PolicyGlobalConcurrencyArgs {
}

export interface PolicyGlobalConcurrencyResult {
  value: number;
}

export interface PolicyNodeConcurrencyArgs {
  actionPath: string[];
}

export interface PolicyNodeConcurrencyResult {
  value: number;
}

export interface ProjectArgs {
  projectionId: string;
  value: unknown;
  label?: string;
}

export interface ShapeResponseArgs {
  response: unknown;
  itemsPath?: string[];
  mode?: string;
}

export interface SleepArgs {
  delayMs: number;
}

export interface SleepResult {
}

export interface TransportCallArgs {
  name: string;
  request: Record<string, unknown>;
}

export interface TransportCallResult {
  statusCode?: number;
  headers?: Record<string, string[]>;
  body?: unknown;
  rawBody?: string;
  nextPageToken?: string;
  metadata?: Record<string, unknown>;
  items?: unknown[];
  raw?: Record<string, unknown>;
}

// HostError envelope (see pkg/hostbus/error.go):
//
// async capabilities reject with an object shaped
//   { name, message, retryable, code, capability? }
// where `message` is prefixed with the capability ID
// ("cache.getMany: <message>"). Read `err.capability`
// directly rather than regexing the message string;
// the prefix is stable but subject to future evolution.
//
// sync capabilities throw a native Go error whose
// message is the same "<capability>: <message>"
// string; the structured fields are not yet
// surfaced to JS on the sync path.

export interface CapabilityArgs {
  "cache.getMany": CacheGetManyArgs;
  "cache.setMany": CacheSetManyArgs;
  "config.get": ConfigGetArgs;
  "loadFusedSiblingResponses": LoadFusedSiblingResponsesArgs;
  "loadShapedResponse": LoadShapedResponseArgs;
  "log.debug": LogArgs;
  "log.error": LogArgs;
  "log.info": LogArgs;
  "log.warn": LogArgs;
  "phase.observe": PhaseObserveArgs;
  "phase.wants": PhaseWantsArgs;
  "policy.globalConcurrency": PolicyGlobalConcurrencyArgs;
  "policy.nodeConcurrency": PolicyNodeConcurrencyArgs;
  "project": ProjectArgs;
  "shapeResponse": ShapeResponseArgs;
  "sleep": SleepArgs;
  "transport.query": TransportCallArgs;
  "transport.request": TransportCallArgs;
  "transport.search": TransportCallArgs;
}

export interface CapabilityResults {
  "cache.getMany": CacheGetManyResult;
  "cache.setMany": CacheSetManyResult;
  "config.get": unknown;
  "loadFusedSiblingResponses": LoadFusedSiblingResponsesResult;
  "loadShapedResponse": LoadShapedResponseResult;
  "log.debug": LogResult;
  "log.error": LogResult;
  "log.info": LogResult;
  "log.warn": LogResult;
  "phase.observe": PhaseObserveResult;
  "phase.wants": boolean;
  "policy.globalConcurrency": PolicyGlobalConcurrencyResult;
  "policy.nodeConcurrency": PolicyNodeConcurrencyResult;
  "project": unknown;
  "shapeResponse": unknown;
  "sleep": SleepResult;
  "transport.query": TransportCallResult;
  "transport.request": TransportCallResult;
  "transport.search": TransportCallResult;
}

export interface HostCapabilities {
  cache: {
    getMany(args: CacheGetManyArgs): Promise<CacheGetManyResult>;
    setMany(args: CacheSetManyArgs): Promise<CacheSetManyResult>;
  };
  config: {
    get(args: ConfigGetArgs): unknown;
  };
  loadFusedSiblingResponses(args: LoadFusedSiblingResponsesArgs): Promise<LoadFusedSiblingResponsesResult>;
  loadShapedResponse(args: LoadShapedResponseArgs): Promise<LoadShapedResponseResult>;
  log: {
    debug(args: LogArgs): LogResult;
    error(args: LogArgs): LogResult;
    info(args: LogArgs): LogResult;
    warn(args: LogArgs): LogResult;
  };
  phase: {
    observe(args: PhaseObserveArgs): PhaseObserveResult;
    wants(args: PhaseWantsArgs): boolean;
  };
  policy: {
    globalConcurrency(args: PolicyGlobalConcurrencyArgs): PolicyGlobalConcurrencyResult;
    nodeConcurrency(args: PolicyNodeConcurrencyArgs): PolicyNodeConcurrencyResult;
  };
  project(args: ProjectArgs): unknown;
  shapeResponse(args: ShapeResponseArgs): unknown;
  sleep(args: SleepArgs): Promise<SleepResult>;
  transport: {
    query(args: TransportCallArgs): Promise<TransportCallResult>;
    request(args: TransportCallArgs): Promise<TransportCallResult>;
    search(args: TransportCallArgs): Promise<TransportCallResult>;
  };
  call<A extends keyof CapabilityArgs>(id: A, args: CapabilityArgs[A]): Promise<CapabilityResults[A]>;
}
