// Code generated by cmd/baton-ts-sdk from baton-sdk v0.18.4. DO NOT EDIT.

export type ActionType =
    | "ACTION_TYPE_UNSPECIFIED"
    | "ACTION_TYPE_DYNAMIC"
    | "ACTION_TYPE_ACCOUNT"
    | "ACTION_TYPE_ACCOUNT_UPDATE_PROFILE"
    | "ACTION_TYPE_ACCOUNT_DISABLE"
    | "ACTION_TYPE_ACCOUNT_ENABLE"
    | "ACTION_TYPE_RESOURCE_CREATE"
    | "ACTION_TYPE_RESOURCE_DELETE"
    | "ACTION_TYPE_RESOURCE_ENABLE"
    | "ACTION_TYPE_RESOURCE_DISABLE";

export type AgentTrait_AgentStatus =
    | "AGENT_STATUS_UNSPECIFIED"
    | "AGENT_STATUS_READY"
    | "AGENT_STATUS_DISABLED"
    | "AGENT_STATUS_DELETED";

export type AppTrait_AppFlag =
    | "APP_FLAG_UNSPECIFIED"
    | "APP_FLAG_HIDDEN"
    | "APP_FLAG_INACTIVE"
    | "APP_FLAG_SAML"
    | "APP_FLAG_OIDC"
    | "APP_FLAG_BOOKMARK";

export type BatonActionStatus =
    | "BATON_ACTION_STATUS_UNSPECIFIED"
    | "BATON_ACTION_STATUS_UNKNOWN"
    | "BATON_ACTION_STATUS_PENDING"
    | "BATON_ACTION_STATUS_RUNNING"
    | "BATON_ACTION_STATUS_COMPLETE"
    | "BATON_ACTION_STATUS_FAILED";

export type Capability =
    | "CAPABILITY_UNSPECIFIED"
    | "CAPABILITY_PROVISION"
    | "CAPABILITY_SYNC"
    | "CAPABILITY_EVENT_FEED"
    | "CAPABILITY_TICKETING"
    | "CAPABILITY_ACCOUNT_PROVISIONING"
    | "CAPABILITY_CREDENTIAL_ROTATION"
    | "CAPABILITY_RESOURCE_CREATE"
    | "CAPABILITY_RESOURCE_DELETE"
    | "CAPABILITY_SYNC_SECRETS"
    | "CAPABILITY_ACTIONS"
    | "CAPABILITY_TARGETED_SYNC"
    | "CAPABILITY_EVENT_FEED_V2"
    | "CAPABILITY_SERVICE_MODE_TARGETED_SYNC";

export type CapabilityDetailCredentialOption =
    | "CAPABILITY_DETAIL_CREDENTIAL_OPTION_UNSPECIFIED"
    | "CAPABILITY_DETAIL_CREDENTIAL_OPTION_NO_PASSWORD"
    | "CAPABILITY_DETAIL_CREDENTIAL_OPTION_RANDOM_PASSWORD"
    | "CAPABILITY_DETAIL_CREDENTIAL_OPTION_SSO"
    | "CAPABILITY_DETAIL_CREDENTIAL_OPTION_ENCRYPTED_PASSWORD";

export type DeviceOS_OsType =
    | "OS_TYPE_UNSPECIFIED"
    | "OS_TYPE_WINDOWS"
    | "OS_TYPE_WINDOWS_MOBILE"
    | "OS_TYPE_LINUX"
    | "OS_TYPE_ANDROID"
    | "OS_TYPE_MACOS"
    | "OS_TYPE_IOS"
    | "OS_TYPE_IPADOS"
    | "OS_TYPE_SOLARIS"
    | "OS_TYPE_AIX"
    | "OS_TYPE_HPUX"
    | "OS_TYPE_CHROMEOS"
    | "OS_TYPE_OTHER";

export type Entitlement_PurposeValue =
    | "PURPOSE_VALUE_UNSPECIFIED"
    | "PURPOSE_VALUE_ASSIGNMENT"
    | "PURPOSE_VALUE_PERMISSION"
    | "PURPOSE_VALUE_OWNERSHIP";

export type EventType =
    | "EVENT_TYPE_UNSPECIFIED"
    | "EVENT_TYPE_USAGE"
    | "EVENT_TYPE_RESOURCE_CHANGE"
    | "EVENT_TYPE_CREATE_GRANT"
    | "EVENT_TYPE_CREATE_REVOKE";

export type ManagedDeviceTrait_Compliance =
    | "COMPLIANCE_UNSPECIFIED"
    | "COMPLIANCE_COMPLIANT"
    | "COMPLIANCE_NONCOMPLIANT"
    | "COMPLIANCE_IN_GRACE_PERIOD"
    | "COMPLIANCE_ERROR";

export type ManagedDeviceTrait_DeviceType =
    | "DEVICE_TYPE_UNSPECIFIED"
    | "DEVICE_TYPE_SERVER"
    | "DEVICE_TYPE_DESKTOP"
    | "DEVICE_TYPE_LAPTOP"
    | "DEVICE_TYPE_TABLET"
    | "DEVICE_TYPE_MOBILE"
    | "DEVICE_TYPE_VIRTUAL"
    | "DEVICE_TYPE_OTHER";

export type ManagedDeviceTrait_ManagementState =
    | "MANAGEMENT_STATE_UNSPECIFIED"
    | "MANAGEMENT_STATE_MANAGED"
    | "MANAGEMENT_STATE_UNMANAGED"
    | "MANAGEMENT_STATE_PENDING"
    | "MANAGEMENT_STATE_RETIRED"
    | "MANAGEMENT_STATE_WIPED";

export type NonHumanIdentityTrait_NhiType =
    | "NHI_TYPE_UNSPECIFIED"
    | "NHI_TYPE_APP_REGISTRATION"
    | "NHI_TYPE_ASSUMABLE_ROLE"
    | "NHI_TYPE_MANAGED_IDENTITY";

export type RateLimitDescription_Status =
    | "STATUS_UNSPECIFIED"
    | "STATUS_OK"
    | "STATUS_OVERLIMIT"
    | "STATUS_ERROR";

export type ResourceType_Trait =
    | "TRAIT_UNSPECIFIED"
    | "TRAIT_USER"
    | "TRAIT_GROUP"
    | "TRAIT_ROLE"
    | "TRAIT_APP"
    | "TRAIT_SECRET"
    | "TRAIT_SECURITY_INSIGHT"
    | "TRAIT_SCOPE_BINDING"
    | "TRAIT_VENDOR"
    | "TRAIT_VENDOR_AGREEMENT"
    | "TRAIT_LICENSE_PROFILE"
    | "TRAIT_AGENT"
    | "TRAIT_MANAGED_DEVICE";

export type Resource_CreationSource =
    | "CREATION_SOURCE_UNSPECIFIED"
    | "CREATION_SOURCE_CONNECTOR_LIST_RESOURCES"
    | "CREATION_SOURCE_CONNECTOR_LIST_GRANTS_PRINCIPAL_JIT";

export type RiskFactor_Severity =
    | "SEVERITY_UNSPECIFIED"
    | "SEVERITY_LOW"
    | "SEVERITY_MEDIUM"
    | "SEVERITY_HIGH"
    | "SEVERITY_CRITICAL";

export type SecretTrait_CredentialType =
    | "CREDENTIAL_TYPE_UNSPECIFIED"
    | "CREDENTIAL_TYPE_STATIC_SECRET"
    | "CREDENTIAL_TYPE_ASYMMETRIC_KEY"
    | "CREDENTIAL_TYPE_CERTIFICATE";

export type UserTrait_AccountType =
    | "ACCOUNT_TYPE_UNSPECIFIED"
    | "ACCOUNT_TYPE_HUMAN"
    | "ACCOUNT_TYPE_SERVICE"
    | "ACCOUNT_TYPE_SYSTEM";

export type UserTrait_Status_Status =
    | "STATUS_UNSPECIFIED"
    | "STATUS_ENABLED"
    | "STATUS_DISABLED"
    | "STATUS_DELETED";

export type VendorAgreementTrait_PricingModel =
    | "PRICING_MODEL_UNSPECIFIED"
    | "PRICING_MODEL_UNKNOWN"
    | "PRICING_MODEL_PER_SEAT"
    | "PRICING_MODEL_PER_LICENSE"
    | "PRICING_MODEL_FLAT"
    | "PRICING_MODEL_TIERED"
    | "PRICING_MODEL_USAGE";

export type VendorAgreementTrait_RenewalStatus =
    | "RENEWAL_STATUS_UNSPECIFIED"
    | "RENEWAL_STATUS_NOT_STARTED"
    | "RENEWAL_STATUS_INITIATED"
    | "RENEWAL_STATUS_RENEWED"
    | "RENEWAL_STATUS_CANCELLED"
    | "RENEWAL_STATUS_REJECTED"
    | "RENEWAL_STATUS_EXPIRED";


export interface ProtoAnnotation {
    readonly "@type": string;

    readonly [key: string]: unknown;
}


export interface AccountInfo extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.AccountInfo";
    readonly emails?: readonly AccountInfo_Email[];
    readonly login: string;
    readonly loginAliases?: readonly string[];
    readonly profile?: Record<string, unknown>;
}

export interface AccountInfo_Email {
    readonly address: string;
    readonly isPrimary: boolean;
}

export interface AgentTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.AgentTrait";
    readonly status: AgentTrait_AgentStatus;
    readonly identityResourceId?: ResourceId;
    readonly profile?: Record<string, unknown>;
}

export interface Aliases extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.Aliases";
    readonly ids: readonly string[];
}

export interface AppTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.AppTrait";
    readonly helpUrl: string;
    readonly icon?: AssetRef;
    readonly logo?: AssetRef;
    readonly profile?: Record<string, unknown>;
    readonly flags?: readonly AppTrait_AppFlag[];
    readonly appSourceType: string;
    readonly rawAppSourceType: string;
}

export interface AssetRef extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.AssetRef";
    readonly id: string;
}

export interface AssetServiceGetAssetResponse_Data {
    readonly data: string;
}

export interface AssetServiceGetAssetResponse_Metadata {
    readonly contentType: string;
}

export interface BatonActionSchema extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.BatonActionSchema";
    readonly name: string;
    readonly arguments?: readonly unknown[];
    readonly constraints?: readonly unknown[];
    readonly returnTypes?: readonly unknown[];
    readonly displayName: string;
    readonly description: string;
    readonly actionType?: readonly ActionType[];
    readonly resourceTypeId: string;
}

export interface BatonID extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.BatonID";
}

export interface CapabilityPermission extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.CapabilityPermission";
    readonly permission: string;
}

export interface CapabilityPermissions extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.CapabilityPermissions";
    readonly permissions?: readonly CapabilityPermission[];
}

export interface ChildResourceType extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ChildResourceType";
    readonly resourceTypeId: string;
}

export interface ConfigSchema extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ConfigSchema";
    readonly fields?: readonly Field[];
    readonly displayName: string;
    readonly helpUrl: string;
    readonly icon?: AssetRef;
    readonly logo?: AssetRef;
}

export interface ConnectorAccountCreationSchema extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ConnectorAccountCreationSchema";
    readonly fieldMap: Record<string, ConnectorAccountCreationSchema_Field>;
}

export interface ConnectorAccountCreationSchema_BoolField {
    readonly defaultValue?: boolean;
}

export interface ConnectorAccountCreationSchema_Field {
    readonly displayName: string;
    readonly required: boolean;
    readonly description: string;
    readonly placeholder: string;
    readonly order: number;
    readonly deprecated: boolean;
    readonly stringField?: ConnectorAccountCreationSchema_StringField;
    readonly boolField?: ConnectorAccountCreationSchema_BoolField;
    readonly stringListField?: ConnectorAccountCreationSchema_StringListField;
    readonly intField?: ConnectorAccountCreationSchema_IntField;
    readonly mapField?: ConnectorAccountCreationSchema_MapField;
}

export interface ConnectorAccountCreationSchema_IntField {
    readonly defaultValue?: number;
}

export interface ConnectorAccountCreationSchema_MapField {
    readonly defaultValue: Record<string, ConnectorAccountCreationSchema_Field>;
}

export interface ConnectorAccountCreationSchema_StringField {
    readonly defaultValue?: string;
}

export interface ConnectorAccountCreationSchema_StringListField {
    readonly defaultValue?: readonly string[];
}

export interface ConnectorCapabilities extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ConnectorCapabilities";
    readonly resourceTypeCapabilities?: readonly ResourceTypeCapability[];
    readonly connectorCapabilities?: readonly Capability[];
    readonly credentialDetails?: CredentialDetails;
}

export interface ConnectorMetadata extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ConnectorMetadata";
    readonly displayName: string;
    readonly helpUrl: string;
    readonly icon?: AssetRef;
    readonly logo?: AssetRef;
    readonly profile?: Record<string, unknown>;
    readonly annotations?: readonly ProtoAnnotation[];
    readonly description: string;
    readonly capabilities?: ConnectorCapabilities;
    readonly accountCreationSchema?: ConnectorAccountCreationSchema;
}

export interface CreateAccountResponse_ActionRequiredResult {
    readonly resource?: Resource;
    readonly message: string;
    readonly isCreateAccountResult: boolean;
}

export interface CreateAccountResponse_AlreadyExistsResult {
    readonly resource?: Resource;
    readonly isCreateAccountResult: boolean;
}

export interface CreateAccountResponse_InProgressResult {
    readonly resource?: Resource;
    readonly isCreateAccountResult: boolean;
}

export interface CreateAccountResponse_SuccessResult {
    readonly resource?: Resource;
    readonly isCreateAccountResult: boolean;
    readonly invitationExpiresAt?: string;
}

export interface CreateGrantEvent extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.CreateGrantEvent";
    readonly entitlement: Entitlement;
    readonly principal: Resource;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface CreateRevokeEvent extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.CreateRevokeEvent";
    readonly entitlement: Entitlement;
    readonly principal: Resource;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface CredentialDetails extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.CredentialDetails";
    readonly capabilityAccountProvisioning?: CredentialDetailsAccountProvisioning;
    readonly capabilityCredentialRotation?: CredentialDetailsCredentialRotation;
}

export interface CredentialDetailsAccountProvisioning extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.CredentialDetailsAccountProvisioning";
    readonly supportedCredentialOptions?: readonly CapabilityDetailCredentialOption[];
    readonly preferredCredentialOption: CapabilityDetailCredentialOption;
}

export interface CredentialDetailsCredentialRotation extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.CredentialDetailsCredentialRotation";
    readonly supportedCredentialOptions?: readonly CapabilityDetailCredentialOption[];
    readonly preferredCredentialOption: CapabilityDetailCredentialOption;
}

export interface CredentialOptions extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.CredentialOptions";
    readonly randomPassword?: CredentialOptions_RandomPassword;
    readonly noPassword?: CredentialOptions_NoPassword;
    readonly sso?: CredentialOptions_SSO;
    readonly encryptedPassword?: CredentialOptions_EncryptedPassword;
    readonly forceChangeAtNextLogin: boolean;
}

export interface CredentialOptions_EncryptedPassword {
    readonly encryptedPasswords: readonly EncryptedData[];
}

export interface CredentialOptions_NoPassword {
}

export interface CredentialOptions_RandomPassword {
    readonly length: string;
    readonly constraints?: readonly PasswordConstraint[];
}

export interface CredentialOptions_SSO {
    readonly ssoProvider: string;
}

export interface DeviceOS extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.DeviceOS";
    readonly type: DeviceOS_OsType;
    readonly name: string;
    readonly version: string;
    readonly build: string;
}

export interface ETag extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ETag";
    readonly value: string;
    readonly entitlementId: string;
}

export interface ETagMatch extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ETagMatch";
    readonly entitlementId: string;
}

export interface ETagMetadata extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ETagMetadata";
    readonly metadata?: Record<string, unknown>;
}

export interface EncryptedData extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.EncryptedData";
    readonly provider: string;
    readonly keyId: string;
    readonly name: string;
    readonly description: string;
    readonly schema: string;
    readonly encryptedBytes: string;
    readonly keyIds?: readonly string[];
}

export interface EncryptionConfig extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.EncryptionConfig";
    readonly principal?: Resource;
    readonly provider: string;
    readonly keyId: string;
    readonly jwkPublicKeyConfig?: EncryptionConfig_JWKPublicKeyConfig;
}

export interface EncryptionConfig_JWKPublicKeyConfig {
    readonly pubKey: string;
}

export interface Entitlement extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.Entitlement";
    readonly resource: Resource;
    readonly id: string;
    readonly displayName: string;
    readonly description: string;
    readonly grantableTo?: readonly ResourceType[];
    readonly annotations?: readonly ProtoAnnotation[];
    readonly purpose: Entitlement_PurposeValue;
    readonly slug: string;
}

export interface EntitlementExclusionGroup extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.EntitlementExclusionGroup";
    readonly exclusionGroupId: string;
    readonly order: number;
    readonly isDefault: boolean;
    readonly scopeToResource: boolean;
}

export interface EntitlementImmutable extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.EntitlementImmutable";
    readonly sourceId: string;
    readonly metadata?: Record<string, unknown>;
}

export interface Event extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.Event";
    readonly id: string;
    readonly occurredAt?: string;
    readonly usageEvent?: UsageEvent;
    readonly grantEvent?: GrantEvent;
    readonly revokeEvent?: RevokeEvent;
    readonly resourceChangeEvent?: ResourceChangeEvent;
    readonly createGrantEvent?: CreateGrantEvent;
    readonly createRevokeEvent?: CreateRevokeEvent;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface EventFeedMetadata extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.EventFeedMetadata";
    readonly id: string;
    readonly supportedEventTypes?: readonly EventType[];
}

export interface ExternalId extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ExternalId";
    readonly id: string;
    readonly link: string;
    readonly description: string;
}

export interface ExternalLink extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ExternalLink";
    readonly url: string;
}

export interface ExternalResourceMatch extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ExternalResourceMatch";
    readonly resourceType: ResourceType_Trait;
    readonly key: string;
    readonly value: string;
}

export interface ExternalResourceMatchAll extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ExternalResourceMatchAll";
    readonly resourceType: ResourceType_Trait;
}

export interface ExternalResourceMatchID extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ExternalResourceMatchID";
    readonly id: string;
}

export interface ExternalTicketRef extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ExternalTicketRef";
    readonly id: string;
    readonly externalTicketProvisionerConfigId: string;
}

export interface ExternalTicketSettings extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ExternalTicketSettings";
    readonly enabled: boolean;
}

export interface Field extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.Field";
    readonly name: string;
    readonly helpUrl: string;
    readonly displayName: string;
    readonly placeholder: string;
    readonly str?: StringField;
    readonly select?: SelectField;
    readonly random?: RandomStringField;
    readonly file?: FileField;
}

export interface FileField extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.FileField";
    readonly secret: boolean;
    readonly valueValidator?: unknown;
    readonly allowedExtensions?: readonly string[];
}

export interface Grant extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.Grant";
    readonly entitlement: Entitlement;
    readonly principal: Resource;
    readonly id: string;
    readonly sources?: GrantSources;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface GrantAlreadyExists extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.GrantAlreadyExists";
}

export interface GrantAlreadyRevoked extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.GrantAlreadyRevoked";
}

export interface GrantEvent extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.GrantEvent";
    readonly grant?: Grant;
}

export interface GrantExpandable extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.GrantExpandable";
    readonly entitlementIds: readonly string[];
    readonly shallow: boolean;
    readonly resourceTypeIds?: readonly string[];
}

export interface GrantImmutable extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.GrantImmutable";
    readonly sourceId: string;
    readonly metadata?: Record<string, unknown>;
}

export interface GrantMetadata extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.GrantMetadata";
    readonly metadata?: Record<string, unknown>;
}

export interface GrantReplaced extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.GrantReplaced";
    readonly replacedGrantId: string;
}

export interface GrantSources extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.GrantSources";
    readonly sources: Record<string, GrantSources_GrantSource>;
}

export interface GrantSources_GrantSource {
    readonly isDirect: boolean;
}

export interface GroupTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.GroupTrait";
    readonly icon?: AssetRef;
    readonly profile?: Record<string, unknown>;
    readonly groupSourceType: string;
    readonly rawGroupSourceType: string;
}

export interface InsertResourceGrants extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.InsertResourceGrants";
}

export interface Issue extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.Issue";
    readonly value: string;
    readonly severity: string;
}

export interface LicenseProfileTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.LicenseProfileTrait";
    readonly licenseName: string;
    readonly purchasedSeats: string;
    readonly consumedSeats: string;
    readonly costPerUnitInCents: string;
    readonly currency: string;
    readonly entitlementIds?: readonly string[];
}

export interface LineItem extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.LineItem";
    readonly productOrServiceName: string;
    readonly quantity: number;
    readonly unit: string;
    readonly pricePerUnit?: Money;
    readonly totalPrice?: Money;
}

export interface LocalCredentialOptions extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.LocalCredentialOptions";
    readonly randomPassword?: LocalCredentialOptions_RandomPassword;
    readonly noPassword?: LocalCredentialOptions_NoPassword;
    readonly sso?: LocalCredentialOptions_SSO;
    readonly plaintextPassword?: LocalCredentialOptions_PlaintextPassword;
    readonly forceChangeAtNextLogin: boolean;
}

export interface LocalCredentialOptions_NoPassword {
}

export interface LocalCredentialOptions_PlaintextPassword {
    readonly plaintextPassword: string;
}

export interface LocalCredentialOptions_RandomPassword {
    readonly length: string;
    readonly constraints?: readonly PasswordConstraint[];
}

export interface LocalCredentialOptions_SSO {
    readonly ssoProvider: string;
}

export interface ManagedDeviceTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ManagedDeviceTrait";
    readonly serial: string;
    readonly udid: string;
    readonly hardwareHash: string;
    readonly deviceType: ManagedDeviceTrait_DeviceType;
    readonly model: string;
    readonly vendor: string;
    readonly os?: DeviceOS;
    readonly compliance: ManagedDeviceTrait_Compliance;
    readonly isEncrypted?: boolean;
    readonly isSupervised?: boolean;
    readonly isPersonal?: boolean;
    readonly managementState: ManagedDeviceTrait_ManagementState;
    readonly enrolledAt?: string;
}

export interface Money extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.Money";
    readonly amountMinor: string;
    readonly currencyCode: string;
}

export interface NonHumanIdentityTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.NonHumanIdentityTrait";
    readonly nhiType: NonHumanIdentityTrait_NhiType;
    readonly nhiDetail: string;
}

export interface OptInRequired extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.OptInRequired";
}

export interface PasswordConstraint extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.PasswordConstraint";
    readonly charSet: string;
    readonly minCount: number;
}

export interface PlaintextData extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.PlaintextData";
    readonly name: string;
    readonly description: string;
    readonly schema: string;
    readonly bytes: string;
}

export interface RandomStringField extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.RandomStringField";
    readonly length: number;
}

export interface RateLimitDescription extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.RateLimitDescription";
    readonly status: RateLimitDescription_Status;
    readonly limit: string;
    readonly remaining: string;
    readonly resetAt?: string;
}

export interface RawId extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.RawId";
    readonly id: string;
}

export interface RequestId extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.RequestId";
    readonly requestId: string;
}

export interface Resource extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.Resource";
    readonly id: ResourceId;
    readonly parentResourceId?: ResourceId;
    readonly displayName: string;
    readonly annotations?: readonly ProtoAnnotation[];
    readonly description: string;
    readonly batonResource: boolean;
    readonly externalId?: ExternalId;
    readonly creationSource: Resource_CreationSource;
}

export interface ResourceChangeEvent extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ResourceChangeEvent";
    readonly resourceId: ResourceId;
    readonly parentResourceId?: ResourceId;
}

export interface ResourceDoesNotExist extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ResourceDoesNotExist";
}

export interface ResourceId extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ResourceId";
    readonly resourceType: string;
    readonly resource: string;
    readonly batonResource: boolean;
}

export interface ResourceType extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ResourceType";
    readonly id: string;
    readonly displayName: string;
    readonly traits?: readonly ResourceType_Trait[];
    readonly annotations?: readonly ProtoAnnotation[];
    readonly description: string;
    readonly sourcedExternally: boolean;
}

export interface ResourceTypeCapability extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ResourceTypeCapability";
    readonly resourceType?: ResourceType;
    readonly capabilities?: readonly Capability[];
    readonly permissions?: CapabilityPermissions;
    readonly optInRequired: boolean;
    readonly skipSyncAnomalyDetection: boolean;
}

export interface RevokeEvent extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.RevokeEvent";
    readonly entitlement?: Entitlement;
    readonly principal?: Resource;
}

export interface RiskFactor extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.RiskFactor";
    readonly description: string;
    readonly severity: RiskFactor_Severity;
}

export interface RiskScore extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.RiskScore";
    readonly value: string;
    readonly factors?: readonly string[];
    readonly normalizedScore: number;
    readonly sourceScore: string;
    readonly riskFactors?: readonly RiskFactor[];
}

export interface RoleScopeCondition extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.RoleScopeCondition";
    readonly expression: string;
}

export interface RoleScopeConditions extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.RoleScopeConditions";
    readonly type: string;
    readonly conditions?: readonly RoleScopeCondition[];
}

export interface RoleTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.RoleTrait";
    readonly profile?: Record<string, unknown>;
    readonly roleScopeConditions?: RoleScopeConditions;
}

export interface ScopeBindingTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.ScopeBindingTrait";
    readonly roleId: ResourceId;
    readonly scopeResourceId: ResourceId;
}

export interface SecretTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.SecretTrait";
    readonly profile?: Record<string, unknown>;
    readonly createdAt?: string;
    readonly expiresAt?: string;
    readonly lastUsedAt?: string;
    readonly createdById?: ResourceId;
    readonly identityId?: ResourceId;
    readonly credentialType: SecretTrait_CredentialType;
    readonly credentialDetail: string;
}

export interface SecurityInsightTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.SecurityInsightTrait";
    readonly riskScore?: RiskScore;
    readonly issue?: Issue;
    readonly observedAt?: string;
    readonly user?: SecurityInsightTrait_UserTarget;
    readonly resourceId?: ResourceId;
    readonly externalResource?: SecurityInsightTrait_ExternalResourceTarget;
    readonly appUser?: SecurityInsightTrait_AppUserTarget;
}

export interface SecurityInsightTrait_AppUserTarget {
    readonly email: string;
    readonly externalId: string;
}

export interface SecurityInsightTrait_ExternalResourceTarget {
    readonly externalId: string;
    readonly appHint: string;
}

export interface SecurityInsightTrait_UserTarget {
    readonly email: string;
}

export interface SelectField extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.SelectField";
    readonly items?: readonly SelectField_Item[];
}

export interface SelectField_Item {
    readonly displayName: string;
    readonly value: string;
}

export interface SessionStoreUsage extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.SessionStoreUsage";
    readonly kind: string;
    readonly ops?: readonly SessionStoreUsage_OpStats[];
}

export interface SessionStoreUsage_OpStats {
    readonly op: string;
    readonly count: string;
    readonly errors: string;
    readonly timeouts: string;
    readonly totalMs: string;
    readonly maxMs: string;
}

export interface SkipEntitlements extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.SkipEntitlements";
}

export interface SkipEntitlementsAndGrants extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.SkipEntitlementsAndGrants";
}

export interface SkipGrants extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.SkipGrants";
}

export interface SkipSyncAnomalyDetection extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.SkipSyncAnomalyDetection";
}

export interface StringField extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.StringField";
    readonly secret: boolean;
    readonly valueValidator?: unknown;
}

export interface Ticket extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.Ticket";
    readonly id: string;
    readonly displayName: string;
    readonly description: string;
    readonly assignees?: readonly Resource[];
    readonly reporter?: Resource;
    readonly status?: TicketStatus;
    readonly type?: TicketType;
    readonly labels?: readonly string[];
    readonly url: string;
    readonly customFields: Record<string, TicketCustomField>;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    readonly completedAt?: string;
    readonly requestedFor?: Resource;
}

export interface TicketCustomField extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketCustomField";
    readonly id: string;
    readonly displayName: string;
    readonly required: boolean;
    readonly stringValue?: TicketCustomFieldStringValue;
    readonly stringValues?: TicketCustomFieldStringValues;
    readonly boolValue?: TicketCustomFieldBoolValue;
    readonly timestampValue?: TicketCustomFieldTimestampValue;
    readonly pickStringValue?: TicketCustomFieldPickStringValue;
    readonly pickMultipleStringValues?: TicketCustomFieldPickMultipleStringValues;
    readonly pickObjectValue?: TicketCustomFieldPickObjectValue;
    readonly pickMultipleObjectValues?: TicketCustomFieldPickMultipleObjectValues;
    readonly numberValue?: TicketCustomFieldNumberValue;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface TicketCustomFieldBoolValue extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketCustomFieldBoolValue";
    readonly value: boolean;
}

export interface TicketCustomFieldNumberValue extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketCustomFieldNumberValue";
    readonly value?: number;
    readonly defaultValue?: number;
}

export interface TicketCustomFieldObjectValue extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketCustomFieldObjectValue";
    readonly id: string;
    readonly displayName: string;
}

export interface TicketCustomFieldPickMultipleObjectValues extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketCustomFieldPickMultipleObjectValues";
    readonly values?: readonly TicketCustomFieldObjectValue[];
    readonly allowedValues?: readonly TicketCustomFieldObjectValue[];
    readonly defaultValues?: readonly TicketCustomFieldObjectValue[];
}

export interface TicketCustomFieldPickMultipleStringValues extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketCustomFieldPickMultipleStringValues";
    readonly values?: readonly string[];
    readonly allowedValues?: readonly string[];
    readonly defaultValues?: readonly string[];
}

export interface TicketCustomFieldPickObjectValue extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketCustomFieldPickObjectValue";
    readonly value?: TicketCustomFieldObjectValue;
    readonly allowedValues?: readonly TicketCustomFieldObjectValue[];
    readonly defaultValue?: TicketCustomFieldObjectValue;
}

export interface TicketCustomFieldPickStringValue extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketCustomFieldPickStringValue";
    readonly value: string;
    readonly allowedValues?: readonly string[];
    readonly defaultValue: string;
}

export interface TicketCustomFieldStringValue extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketCustomFieldStringValue";
    readonly value: string;
    readonly defaultValue: string;
}

export interface TicketCustomFieldStringValues extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketCustomFieldStringValues";
    readonly values?: readonly string[];
    readonly defaultValues?: readonly string[];
}

export interface TicketCustomFieldTimestampValue extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketCustomFieldTimestampValue";
    readonly value?: string;
    readonly defaultValue?: string;
}

export interface TicketRequest extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketRequest";
    readonly displayName: string;
    readonly description: string;
    readonly status?: TicketStatus;
    readonly type?: TicketType;
    readonly labels?: readonly string[];
    readonly customFields: Record<string, TicketCustomField>;
    readonly requestedFor?: Resource;
}

export interface TicketSchema extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketSchema";
    readonly id: string;
    readonly displayName: string;
    readonly types?: readonly TicketType[];
    readonly statuses?: readonly TicketStatus[];
    readonly customFields: Record<string, TicketCustomField>;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface TicketStatus extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketStatus";
    readonly id: string;
    readonly displayName: string;
}

export interface TicketType extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketType";
    readonly id: string;
    readonly displayName: string;
}

export interface TicketsServiceBulkCreateTicketsRequest extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceBulkCreateTicketsRequest";
    readonly ticketRequests?: readonly TicketsServiceCreateTicketRequest[];
}

export interface TicketsServiceBulkCreateTicketsResponse extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceBulkCreateTicketsResponse";
    readonly tickets?: readonly TicketsServiceCreateTicketResponse[];
}

export interface TicketsServiceBulkGetTicketsRequest extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceBulkGetTicketsRequest";
    readonly ticketRequests?: readonly TicketsServiceGetTicketRequest[];
}

export interface TicketsServiceBulkGetTicketsResponse extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceBulkGetTicketsResponse";
    readonly tickets?: readonly TicketsServiceGetTicketResponse[];
}

export interface TicketsServiceCreateTicketRequest extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceCreateTicketRequest";
    readonly request?: TicketRequest;
    readonly schema?: TicketSchema;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface TicketsServiceCreateTicketResponse extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceCreateTicketResponse";
    readonly ticket?: Ticket;
    readonly annotations?: readonly ProtoAnnotation[];
    readonly error: string;
}

export interface TicketsServiceGetTicketRequest extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceGetTicketRequest";
    readonly id: string;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface TicketsServiceGetTicketResponse extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceGetTicketResponse";
    readonly ticket?: Ticket;
    readonly annotations?: readonly ProtoAnnotation[];
    readonly error: string;
}

export interface TicketsServiceGetTicketSchemaRequest extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceGetTicketSchemaRequest";
    readonly id: string;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface TicketsServiceGetTicketSchemaResponse extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceGetTicketSchemaResponse";
    readonly schema?: TicketSchema;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface TicketsServiceListTicketSchemasRequest extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceListTicketSchemasRequest";
    readonly pageSize: number;
    readonly pageToken: string;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface TicketsServiceListTicketSchemasResponse extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.TicketsServiceListTicketSchemasResponse";
    readonly list?: readonly TicketSchema[];
    readonly nextPageToken: string;
    readonly annotations?: readonly ProtoAnnotation[];
}

export interface UsageEvent extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.UsageEvent";
    readonly targetResource?: Resource;
    readonly actorResource?: Resource;
}

export interface UserTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.UserTrait";
    readonly emails?: readonly UserTrait_Email[];
    readonly status: UserTrait_Status;
    readonly profile?: Record<string, unknown>;
    readonly icon?: AssetRef;
    readonly accountType: UserTrait_AccountType;
    readonly login: string;
    readonly loginAliases?: readonly string[];
    readonly employeeIds?: readonly string[];
    readonly createdAt?: string;
    readonly lastLogin?: string;
    readonly mfaStatus?: UserTrait_MFAStatus;
    readonly ssoStatus?: UserTrait_SSOStatus;
    readonly structuredName?: UserTrait_StructuredName;
}

export interface UserTrait_Email {
    readonly address: string;
    readonly isPrimary: boolean;
}

export interface UserTrait_MFAStatus {
    readonly mfaEnabled: boolean;
}

export interface UserTrait_SSOStatus {
    readonly ssoEnabled: boolean;
}

export interface UserTrait_Status {
    readonly status: UserTrait_Status_Status;
    readonly details: string;
}

export interface UserTrait_StructuredName {
    readonly givenName: string;
    readonly familyName: string;
    readonly middleNames?: readonly string[];
    readonly prefix: string;
    readonly suffix: string;
}

export interface V1Identifier extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.V1Identifier";
    readonly id: string;
}

export interface VendorAgreementTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.VendorAgreementTrait";
    readonly agreementName: string;
    readonly startDate?: string;
    readonly endDate?: string;
    readonly lastDateToTerminate?: string;
    readonly autoRenewal: boolean;
    readonly renewalStatus: VendorAgreementTrait_RenewalStatus;
    readonly renewalStatusRaw: string;
    readonly totalValue?: Money;
    readonly lineItems?: readonly LineItem[];
    readonly pricingModel: VendorAgreementTrait_PricingModel;
    readonly externalAccountManagerEmail: string;
    readonly externalAccountManagerName: string;
}

export interface VendorTrait extends ProtoAnnotation  {
    readonly "@type": "type.googleapis.com/c1.connector.v2.VendorTrait";
    readonly vendorId: string;
    readonly vendorName: string;
    readonly vendorDbaName: string;
    readonly websiteDomain: string;
    readonly externalVendorId: string;
    readonly deepLinkUrl: string;
    readonly sourceBusinessId: string;
    readonly sourceEntityId: string;
    readonly trailing30dSpend?: Money;
    readonly trailing365dSpend?: Money;
    readonly ytdSpend?: Money;
}

export type C1ConnectorV2 =
    | AccountInfo
    | AgentTrait
    | Aliases
    | AppTrait
    | AssetRef
    | BatonActionSchema
    | BatonID
    | CapabilityPermission
    | CapabilityPermissions
    | ChildResourceType
    | ConfigSchema
    | ConnectorAccountCreationSchema
    | ConnectorCapabilities
    | ConnectorMetadata
    | CreateGrantEvent
    | CreateRevokeEvent
    | CredentialDetails
    | CredentialDetailsAccountProvisioning
    | CredentialDetailsCredentialRotation
    | CredentialOptions
    | DeviceOS
    | ETag
    | ETagMatch
    | ETagMetadata
    | EncryptedData
    | EncryptionConfig
    | Entitlement
    | EntitlementExclusionGroup
    | EntitlementImmutable
    | Event
    | EventFeedMetadata
    | ExternalId
    | ExternalLink
    | ExternalResourceMatch
    | ExternalResourceMatchAll
    | ExternalResourceMatchID
    | ExternalTicketRef
    | ExternalTicketSettings
    | Field
    | FileField
    | Grant
    | GrantAlreadyExists
    | GrantAlreadyRevoked
    | GrantEvent
    | GrantExpandable
    | GrantImmutable
    | GrantMetadata
    | GrantReplaced
    | GrantSources
    | GroupTrait
    | InsertResourceGrants
    | Issue
    | LicenseProfileTrait
    | LineItem
    | LocalCredentialOptions
    | ManagedDeviceTrait
    | Money
    | NonHumanIdentityTrait
    | OptInRequired
    | PasswordConstraint
    | PlaintextData
    | RandomStringField
    | RateLimitDescription
    | RawId
    | RequestId
    | Resource
    | ResourceChangeEvent
    | ResourceDoesNotExist
    | ResourceId
    | ResourceType
    | ResourceTypeCapability
    | RevokeEvent
    | RiskFactor
    | RiskScore
    | RoleScopeCondition
    | RoleScopeConditions
    | RoleTrait
    | ScopeBindingTrait
    | SecretTrait
    | SecurityInsightTrait
    | SelectField
    | SessionStoreUsage
    | SkipEntitlements
    | SkipEntitlementsAndGrants
    | SkipGrants
    | SkipSyncAnomalyDetection
    | StringField
    | Ticket
    | TicketCustomField
    | TicketCustomFieldBoolValue
    | TicketCustomFieldNumberValue
    | TicketCustomFieldObjectValue
    | TicketCustomFieldPickMultipleObjectValues
    | TicketCustomFieldPickMultipleStringValues
    | TicketCustomFieldPickObjectValue
    | TicketCustomFieldPickStringValue
    | TicketCustomFieldStringValue
    | TicketCustomFieldStringValues
    | TicketCustomFieldTimestampValue
    | TicketRequest
    | TicketSchema
    | TicketStatus
    | TicketType
    | TicketsServiceBulkCreateTicketsRequest
    | TicketsServiceBulkCreateTicketsResponse
    | TicketsServiceBulkGetTicketsRequest
    | TicketsServiceBulkGetTicketsResponse
    | TicketsServiceCreateTicketRequest
    | TicketsServiceCreateTicketResponse
    | TicketsServiceGetTicketRequest
    | TicketsServiceGetTicketResponse
    | TicketsServiceGetTicketSchemaRequest
    | TicketsServiceGetTicketSchemaResponse
    | TicketsServiceListTicketSchemasRequest
    | TicketsServiceListTicketSchemasResponse
    | UsageEvent
    | UserTrait
    | V1Identifier
    | VendorAgreementTrait
    | VendorTrait;

export type ResourceAnnotation =
    | UserTrait
    | GroupTrait
    | RoleTrait
    | AppTrait;

export type EntitlementAnnotation = ProtoAnnotation;
export type GrantAnnotation = GrantExpandable | GrantImmutable | ProtoAnnotation;
export type GrantResponse = GrantAlreadyExists | ProtoAnnotation;
export type RevokeResponse = GrantAlreadyRevoked | ProtoAnnotation;
export type TicketAnnotation = ProtoAnnotation;
