// Code generated by 'go run ./cmd/baton-transport-defaults -declarations'; DO NOT EDIT.

declare namespace TransportDefaults {
  export type TransportKind =
    | "http"
    | "sql"
    | "ldap";

  export type OperationKind =
    | "request"
    | "query"
    | "search";

}
